version: "3.8"
services:
  movie_postgres:
    image: postgres:alpine
    container_name: movie_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5000:5432"
    volumes:
       - ./database_init/init.sql:/docker-entrypoint-initdb.d/init.sql
       - movie_postgres:/var/lib/postgresql/data
    restart: on-failure

  movie_usage_redis:
    image: redis:alpine
    container_name: movie_usage_redis
    working_dir: /var/lib/redis
    environment: 
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD}"]
    ports:
      - "127.0.0.1:6000:6379"
    volumes:
      - movie_redis_data:/var/lib/redis
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    restart: on-failure

  movie_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_backend
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on: 
      - movie_postgres
      - movie_usage_redis
    ports:
      - "3001:3001"
    restart: on-failure

volumes:
  movie_postgres:
  movie_redis_data:
  redis_config: